main: me.doopaderp.flightmedallion.Main
name: flightmedallion
version: 0.1
author: doopaderp

api-version: 1.14

commands:
  giveflightmedallion:

permissions:
  flightmedallion.give:
    description: Gives the player a Medallion of Flight.
    default: op